<?php

define('ASHAPI_URI', 'https://ashapi.heroku.com/videos');
define('ASHAPI_USER', 'cylecarlson');
define('ASHAPI_PASS', 'c9a6fd48075664eebd2f85e419557adcc');

/**
 * Implementation of hook_menu().
 */
function aai_videos_menu() {
	$path = drupal_get_path('module', 'aai_videos');
  $items['videos'] = array(
    'title' => 'Videos',
    'description' => 'Keep up-to-date with the latest in internet coolness.',
    'page callback' => 'aai_videos_list',
    'access arguments' => array('access content'),
    'file' => 'aai_videos.pages.inc',
    'file path' => $path.'/includes',
  );
  $items['videos/%/%'] = array(
    'page callback' => 'aai_videos_operation',
    'page arguments' => array(1,2),
    'access arguments' => array('access content'),
    'file' => 'aai_videos.pages.inc',
    'file path' => $path.'/includes',
  );
  return $items;
}

/**
 * Implementation of hook_block().
 */
function aai_videos_block($op = 'list', $delta = 0, $edit = array()) {
  module_load_include('block.inc', 'aai_videos', 'includes/aai_videos');
  return aai_videos_block_block($op, $delta, $edit);
}

/**
 * Implementation of hook_theme().
 */
function aai_videos_theme() {
  module_load_include('theme.inc', 'aai_videos', 'theme/aai_videos');
  return aai_videos_theme_theme();
}

/**
 * Used to determine if certain site actions are allowed. Right now
 * we only allow certain actions on weekdays.
 *
 * @return Returns TRUE if today is a Saturday or Sunday
 */
function aai_videos_is_allowed() {
	return in_array(date('N'), array(6,7)) ? FALSE : TRUE;
} 

/**
 * Check if the current user has exceeded the limit on this form.
 *
 * @param $id
 *   The video id.
 * @param $name
 *   A unique identifier used in the cookie name
 * @param $set
 *   Boolean used to set the cookie if needed
 * @return
 *   Boolean TRUE if the user has exceeded their limit. FALSE otherwise.
 */
function aai_videos_limit_check($id, $name, $set = FALSE){
  $cookie_name = 'aai-videos-'.$id.'-'.$name;
  // If cookie exists return TRUE
  if(isset($_COOKIE[$cookie_name])) return TRUE;
  if($set){
  	// Set cookie for future checks
  	$time = time();
  	// Expire in 1 day
  	setcookie($cookie_name, $time, $time + 86400, '/');
  }
  return FALSE;
}